### ISSUE TITLE
thread 'main' panicked at 'no entry found for key'

### ISSUE THREAD

**Issue by mntalateyya** [lalrpop/lalrpop#380] opened 2018-05-23 16:31 UTC
build panics without any error message!
This is the most reduced version of the grammar I could make that produces the error:
(Edited)
```
grammar;

pub Expr: Box<Expr> = {
    Bind,
    "func" "{" (Arm ",")* "}",
    Term+,
};

Bind: Bind = {
    <Pattern> "=" <Expr> ";",
};

Term: Box<Expr> = {
    Primitive,
    "(" Expr ")",
};

Arm: (Pattern, Expr) = {
    Pattern "=>" Expr,
};

Pattern = {
    Primitive,
    "(" (Pattern ",")+ Pattern ")",
};

Primitive = {
    r"-?[0-9]*",
};
```
Interestingly, removing any rule from the multiple-rule non-terminals removes the error, so it's probably an ambiguity? but no error message is given. The following stack trace is found
```
...
   8: core::option::expect_failed
             at libcore/option.rs:916
   9: <core::option::Option<T>>::expect
             at /checkout/src/libcore/option.rs:302
  10: <alloc::btree::map::BTreeMap<K, V> as core::ops::index::Index<&'a Q>>::index
             at /checkout/src/liballoc/btree/map.rs:1785
  11: lalrpop::lr1::lane_table::construct::merge::ContextSets::union
             at /home/mnur/.cargo/registry/src/github.com-1ecc6299db9ec823/lalrpop-0.15.2/src/lr1/lane_table/construct/merge.rs:205
  12: lalrpop::lr1::lane_table::construct::merge::Merge::walk
             at /home/mnur/.cargo/registry/src/github.com-1ecc6299db9ec823/lalrpop-0.15.2/src/lr1/lane_table/construct/merge.rs:93
  13: lalrpop::lr1::lane_table::construct::merge::Merge::start
             at /home/mnur/.cargo/registry/src/github.com-1ecc6299db9ec823/lalrpop-0.15.2/src/lr1/lane_table/construct/merge.rs:55
  14: lalrpop::lr1::lane_table::construct::LaneTableConstruct::resolve_inconsistencies
             at /home/mnur/.cargo/registry/src/github.com-1ecc6299db9ec823/lalrpop-0.15.2/src/lr1/lane_table/construct/mod.rs:208
  15: lalrpop::lr1::lane_table::construct::LaneTableConstruct::construct
             at /home/mnur/.cargo/registry/src/github.com-1ecc6299db9ec823/lalrpop-0.15.2/src/lr1/lane_table/construct/mod.rs:79
  16: lalrpop::lr1::lane_table::build_lane_table_states
             at /home/mnur/.cargo/registry/src/github.com-1ecc6299db9ec823/lalrpop-0.15.2/src/lr1/lane_table/mod.rs:17
  17: lalrpop::lr1::build::build_lr1_states
             at /home/mnur/.cargo/registry/src/github.com-1ecc6299db9ec823/lalrpop-0.15.2/src/lr1/build/mod.rs:51
  18: lalrpop::lr1::build_states
             at /home/mnur/.cargo/registry/src/github.com-1ecc6299db9ec823/lalrpop-0.15.2/src/lr1/mod.rs:32
  19: lalrpop::build::emit_recursive_ascent
             at /home/mnur/.cargo/registry/src/github.com-1ecc6299db9ec823/lalrpop-0.15.2/src/build/mod.rs:385
  20: lalrpop::build::process_file_into
             at /home/mnur/.cargo/registry/src/github.com-1ecc6299db9ec823/lalrpop-0.15.2/src/build/mod.rs:129
  21: lalrpop::build::process_file
             at /home/mnur/.cargo/registry/src/github.com-1ecc6299db9ec823/lalrpop-0.15.2/src/build/mod.rs:63
  22: lalrpop::build::process_dir
             at /home/mnur/.cargo/registry/src/github.com-1ecc6299db9ec823/lalrpop-0.15.2/src/build/mod.rs:54
  23: lalrpop::api::Configuration::process_dir
             at /home/mnur/.cargo/registry/src/github.com-1ecc6299db9ec823/lalrpop-0.15.2/src/api/mod.rs:153
  24: lalrpop::api::Configuration::process_current_dir
             at /home/mnur/.cargo/registry/src/github.com-1ecc6299db9ec823/lalrpop-0.15.2/src/api/mod.rs:147
  25: lalrpop::api::process_root
             at /home/mnur/.cargo/registry/src/github.com-1ecc6299db9ec823/lalrpop-0.15.2/src/api/mod.rs:170
  26: build_script_build::main
             at ./build.rs:4
...
  34: _start
```

**Comment by mntalateyya** [comment] 2018-06-07 10:02
I think I can see the problem now. The grammar itself is not ambiguous, but is not LR(1). A primitive can be reduced to either Term or Pattern. Still, better error handling in LALRPOP would be nice.

**Comment by alercah** [comment] 2019-01-08 15:34
Duplicate of #391 likely?

**Comment by Marwes** [comment] 2019-01-08 15:47
Yep, closing and moving the example to #391.

**Closed by Marwes** 2019-01-08 15:47 UTC
