### ISSUE TITLE
Intermittent compile errors

### ISSUE THREAD

**Issue by manoadamro** [lalrpop/lalrpop#672] opened 2022-07-05 12:10 UTC
From time to time, the build will hang on `Blocking waiting for file lock on build directory`.
I've been able to get around this by running `cargo clean` and trying again.

Sometimes the clean will fail:
```
error: could not remove build directory

Caused by:
  failed to remove directory `/mnt/c/.../target/debug/build/libc-d2d302c68ab6c510`

Caused by:
  Directory not empty (os error 39)

```
Rerun it a few times and it will eventually work.

The problem is: when recompiling after a clean, every now and then the compile will fail with one of the following:

```
error: linking with `cc` failed: exit status: 1
```

```
error: could not write output to /mnt/c/.../target/debug/build/az-5d623f28c70f1343/build_sc
ript_build-5d623f28c70f1343.3c88bxwxibepvkux.rcgu.o: Cannot allocate memory
```

```
error: could not compile `tiny-keccak` due to previous error
warning: build failed, waiting for other jobs to finish...
error: linking with `cc` failed: exit status: 1
```
( the exact package here ^ is pretty random and is different each time )

Waiting a little while and trying again, or reinstalling rust from scratch seems to fix it, but it happens often enough that it's quite inconvenient.

It could well be that this is a rustc issue, I'd just never seen these errors before using lalrpop.
Any advice is much appreciated.

Also, is it normal for the build.rs to take an hour to run?
My lalrpop file is about 200 lines and the build script is simply:
```
extern crate lalrpop;

fn main() {
    lalrpop::process_root().unwrap();
}
```

Could this be related?

**Comment by Pat-Lafon** [comment] 2023-11-13 15:38
I've seen `Blocking waiting for file lock on build directory` when I'm building a crate with a long build time and I have my editor open(with Rust-Analyzer) which is also trying to build the same crate on it's side. Thus you end up with contention on the lock file. `cargo clean` then basically nukes everything so that you get to build without contention. I'm not sure what your other errors might be relating too besides that maybe there is some partial state left over from killing the build process on rustc/cargo's side(Or a build script of your dependency).

I'm going to close this issue since it's not reproducible on our side without a lalrpop file that generates this excessive build time(if that is indeed the issue). I'm not sure if there is something here that lalrpop should address. If this is still reproducible or needs a second look, let me know and I will reopen.

**Closed by Pat-Lafon** 2023-11-13 15:38 UTC
