### ISSUE TITLE
Don't emit `#![allow(unused_imports)]`

### ISSUE THREAD

**Issue by kennytm** [lalrpop/lalrpop#111] opened 2016-04-24 10:14 UTC
This prevents the generated code from being able to be `include!()`'ed. Example:

``` rust
// build.rs
extern crate lalrpop;

use lalrpop::Configuration;

fn main() {
    let mut config = Configuration::new();
    config.use_cargo_dir_conventions();
    config.process().unwrap();
}
```

``` rust
// src/parser.lalrpop
/* whatever */
```

``` rust
// src/parser.rs
include!(concat!(env!("OUT_DIR"), "/parser.rs"));
```

Resulting error:

```
<snip>/out/parser.rs:1:3: 1:4 error: an inner attribute is not permitted in this context
<snip>/out/parser.rs:1 #![allow(unused_imports)]
                         ^
<snip>/out/parser.rs:1:3: 1:4 help: place inner attribute at the top of the module or block
```

---

Tested against commit d34f87b33927d6049520092ca862a814688e47ad. Environment:

```
$ rustc -vV
rustc 1.8.0 (db2939409 2016-04-11)
binary: rustc
commit-hash: db2939409db26ab4904372c82492cd3488e4c44e
commit-date: 2016-04-11
host: x86_64-apple-darwin
release: 1.8.0
$ cargo -V
cargo 0.9.0-nightly (8fc3fd8 2016-02-29)
```

**Comment by TyOverby** [comment] 2016-04-25 17:16
A workaround would be:

```rust
mod parser {
    include!(concat!(env!("OUT_DIR"), "/parser.rs"));
}
```

**Comment by Pat-Lafon** [comment] 2023-08-23 20:38
@youknowone Looking through old issues and this one is no longer reproducible. The only `#![allow(unused_imports)]` generated is safely wrapped by a `"mod {}intern_token {{"`

**Comment by yannham** [comment] 2023-09-06 10:45
Following @Pat-Lafon comment, I'm closing for now. Feel free to re-open if we were misled and the issue is actually still present.

**Closed by yannham** 2023-09-06 10:45 UTC
