### ISSUE TITLE
links on doc page are broken

### ISSUE THREAD

**Issue by wtholliday** [lalrpop/lalrpop#642] opened 2022-01-09 17:43 UTC
See here: http://lalrpop.github.io/lalrpop/lexer_tutorial/index.html

**Comment by absurdhero** [comment] 2022-01-18 01:08
I looked into this and the issue is also documented over at #546 .

Looking at `git blame`, the links were all broken in the index.md files in commit 57faab51 last year.
The commit comment says it *fixed* the links so I wonder what changed since then that caused the relative links to need to revert back to the way they were?

**Comment by absurdhero** [comment] 2022-01-18 01:22
I tracked down the source of most of the currently broken links to PR #502. I still don't understand why that was apparently a good change in 2020 and needs to be reverted now.

I think all the issues and PRs need to be paired down to just one. Lots of us users are opening PRs with partial fixes and new issues which is just creating more work for the maintainers :)

Redundant Issues:
#642
#546
#605 

Related and partially redundant PRs:
#631
#627
#615

I'd be happy to review all these and clean them up, nominate one of those existing PRs to remedy it, or make a new one to put this to rest.

**Comment by FrancisRussell** [comment] 2023-01-29 17:14
Just noting that this is still an issue as of January 2023.

**Comment by bryantbiggs** [comment] 2023-03-25 17:58
should be resolved with #724 now

**Comment by nikomatsakis** [comment] 2023-03-25 18:26
Seems to work, indeed.

**Closed by nikomatsakis** 2023-03-25 18:26 UTC
