### ISSUE TITLE
conflicts between `_` and named tokens not detected

### ISSUE THREAD

**Issue by nikomatsakis** [lalrpop/lalrpop#729] opened 2023-03-25 18:23 UTC
The following grammar has a conflict between two regexs that is flagged:

```
Test = {
    r"[a-z]*",
    r"[a-z]*"
};
```

which is flagged

```
  processing file `/home/nmatsakis/versioned/duchess/src/class_info/javap_parser.lalrpop`
  /home/nmatsakis/versioned/duchess/src/class_info/javap_parser.lalrpop:140:5: 140:13 error: ambiguity detected between the terminal `r#"[a-z]*"#` and the terminal `r#"[a-zA-Z][a-zA-Z0-9]*"#`

  --- stderr
        r"[a-z]*",
        ~~~~~~~~~
```

but if I use a `match` with `_`...

```

Test = {
    r"[a-z]*",
    ID
};

match {
    r"[a-z]*" => ID,
    _
}
```

...then I get no errors. This can produce some really confusing failures at parse time.

```

**Comment by dburgener** [comment] 2024-06-21 14:08
I'm not sure if something has changed in the interim since this bug was filed, but I'm getting different results than reported here.

For the first grammar, I get:

```
processing file `issue_729.lalrpop`
issue_729.lalrpop:4:2: 4:10: Conflict detected

    when in this state:
  Test = r#"[a-z]*"# (*) [r#"[a-z]*"#, Eof]
  Test = r#"[a-z]*"# (*) [r#"[a-z]*"#, Eof]

  and looking at a token `r#"[a-z]*"#` we can reduce to a `Test` but we can also
  reduce to a `Test`

issue_729.lalrpop:4:2: 4:10: Conflict detected

    when in this state:
  Test = r#"[a-z]*"# (*) [r#"[a-z]*"#, Eof]
  Test = r#"[a-z]*"# (*) [r#"[a-z]*"#, Eof]

  and looking at a token `Eof` we can reduce to a `Test` but we can also reduce
  to a `Test`
```

And for the second I get:

```
processing file `issue_729.lalrpop`
issue_729.lalrpop:4:2: 4:10 error: ambiguity detected between the terminal `r#"[a-z]*"#` and the terminal `r#"[a-z]*"#`
        r"[a-z]*",
   ~~~~~~~~~
```

So the key issue here, the second grammar producing no errors, seems to have been resolved in the interim.  The difference in error reporting, I'm not sure about, but I think it makes sense to me.  If we list the same terminal multiple times in the body of the grammar, that's just multiple mentions of the same terminal, which is fine, and the issue is that we've written a reduce/reduce conflict as reported.  On the other hand, if we list it in a match, we should also convert all instances to ID.

My my inclination is to close this issue, as it seems to no longer occur, but perhaps I'm missing something.

**Comment by yannham** [comment] 2024-06-21 15:41
I concur. We can always re-open, or open new variation of the issue if needed.

**Comment by dburgener** [comment] 2024-06-21 15:44
Closing, as this seems to no longer reproduce.

**Closed by dburgener** 2024-06-21 15:44 UTC
