### ISSUE TITLE
Getting a  "could not find `lexer` in `__lalrpop_util`"

### ISSUE THREAD

**Issue by wags-1314** [lalrpop/lalrpop#650] opened 2022-02-02 06:01 UTC
I have been following the LALRPOP tutorial and just tried implementing the parenthesized numbers example. But whenever I try to run, I get this error message:
```
bhargav@bhargav-kk:/mnt/c/bhargav/Programming/Language-stuff/brim$ cargo run
   Compiling libc v0.2.116
   ...
   Compiling lalrpop v0.19.7
   Compiling brim v0.1.0 (/mnt/c/bhargav/Programming/Language-stuff/brim)
error[E0432]: unresolved import `self::__lalrpop_util::lexer`
  --> /mnt/c/bhargav/Programming/Language-stuff/brim/target/debug/build/brim-9358516eba536307/out/grammar.rs:22:31
   |
22 |     use self::__lalrpop_util::lexer::Token;
   |                               ^^^^^ could not find `lexer` in `__lalrpop_util`

...
For more information about an error, try `rustc --explain E0432`.
error: could not compile `brim` due to 5 previous errors
```

This is my `main.rs`:
```rust
#[macro_use]
extern crate lalrpop_util;

lalrpop_mod!(pub grammar); // synthesized by LALRPOP

#[test]
fn calculator1() {
    assert!(grammar::TermParser::new().parse("22").is_ok());
    assert!(grammar::TermParser::new().parse("(22)").is_ok());
    assert!(grammar::TermParser::new().parse("((((22))))").is_ok());
    assert!(grammar::TermParser::new().parse("((22)").is_err());
}

fn main() {
    println!("Hello, world!");
}
```
This is my LALRPOP file:
```
use std::str::FromStr;

grammar;

pub Term: i32 = {
    <n:Num> => n,
    "(" <t:Term> ")" => t,
};

Num: i32 = <s:r"[0-9]+"> => i32::from_str(s).unwrap();
```
My `build.rs` which is outside the `src` folder:
```rust
extern crate lalrpop;

fn main() {
    lalrpop::process_root().unwrap();
}
```
And my `Cargo.toml`:
```toml
[package]
name = "brim"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lalrpop-util = "0.19.7"
regex = "1"

[build-dependencies]
lalrpop = { version = "0.19.7", features = ["lexer"] }
```
Any way to fix this?

**Comment by ccleve** [comment] 2022-02-02 19:24
I'm getting the same error. When I open up the generated file in my IDE, CLion, I see:

```
fn token_to_symbol(&self, token_index: usize, token: Self::Token) -> Self::Symbol {
    __token_to_symbol(token_index, token, core::marker::PhantomData::<(&())>)
}

```
with a red squiggle under `Self::Token` that says `the trait bound `T: std::marker::Sized` is not satisfied [E0277] `T` does not have a constant size known at compile-time`

**Comment by allxiao** [comment] 2022-02-08 07:11
I'm getting the same error.
I tried to downgrade to 0.19.6 or earlier versions, but it still reported the same error.

**Comment by allxiao** [comment] 2022-02-08 07:52
Add the `features` setting in the the dependency of `lalrpop-util` will work:

```
[dependencies]
lalrpop-util = { version = "^0.19", features = ["lexer"] }
```

**Comment by pnkfelix** [comment] 2022-02-20 01:22
From what I can tell, this bug is somehow caused by the use of the 2021 edition in newer projects.

If you downgrade to edition=2018, then it will probably resolve the problem for you. Or at least, it did for me.

**Comment by pnkfelix** [comment] 2022-02-20 01:23
see also #616

**Comment by mfdorst** [comment] 2022-03-07 01:41
The tutorial should be updated so people know to enable the `lexer` feature.

**Comment by EMUNES** [comment] 2022-05-25 09:44
> Add the `features` setting in the the dependency of `lalrpop-util` will work:
> 
> ```
> [dependencies]
> lalrpop-util = { version = "^0.19", features = ["lexer"] }
> ```

Great, it sovles my problem. Thanks for your solution!

**Comment by Firstyear** [comment] 2022-12-14 22:57
Just ran into this issue myself, is the tutorial still not updated for 2021?

**Comment by sp3ctum** [comment] 2023-06-10 17:26
I ran into this too. In case there is a little extra time, perhaps the tutorial could be updated to prevent future issues.

**Comment by yannham** [comment] 2023-06-12 08:44
Ah, it seems this would be solved by https://github.com/lalrpop/lalrpop/pull/711, but the PR has stalled for some reason. Sorry for the confusion; will try to get that through.

**Comment by Pat-Lafon** [comment] 2024-05-30 07:10
Closing as completed

**Closed by Pat-Lafon** 2024-05-30 07:10 UTC
