### ISSUE TITLE
How to do associativity

### ISSUE THREAD

**Issue by foophoof** [lalrpop/lalrpop#153] opened 2016-10-01 15:04 UTC
It looks like #67 is working on a nice way to implement associativity, but I was wondering if it's possible at all with todays code. I want something like this:

``` Rust
Expression: ast::Expression = {
    <e1: Expression> "and" <e2: Expression> => ast::Expression::And(Box::new(e1), Box::new(e2)),
    <e1: Expression> "or" <e2: Expression> => ast::Expression::Or(Box::new(e1), Box::new(e2)),
    …
}
```

Assuming the `…` in the definition allows me to parse `foo`, `bar` and `baz`, I want `foo and bar and baz` to be equivalent to `(foo and bar) and baz`.

Or, in terms of the calculator example, I want to be able to parse `1 + 2 + 3` as `(1 + 2) + 3`.

Is this possible at all? I tried using the precedence examples from the calculator example, but that doesn't really work since I want any expression to be valid on both sides of the `and` or `or`.

The YACC file that I'm working on converting just has it as this:

``` yacc
expr : expr keyword_and expr
     | expr keyword_or expr
     | …
     ;
```

**Comment by ahmedcharles** [comment] 2018-01-31 10:36
There isn't a way to do this. Closing as a duplicate of #67.

**Closed by ahmedcharles** 2018-01-31 10:36 UTC
