### ISSUE TITLE
lrgrammar.rs seems to be back in the crate

### ISSUE THREAD

**Issue by Yoric** [lalrpop/lalrpop#409] opened 2018-10-09 14:44 UTC
As of 0.15.2, file `lalrpop/src/parser/lrgrammar.rs` seems to be back in the crate. That's a 3.7 Mb file that doesn't need to be there, and prevents me from updating some dependencies in Firefox :/

Can something be done against that?

**Comment by Marwes** [comment] 2018-10-09 15:28
It might have been published to crates-io by accident (it is only really recent cargo versions that do a good job at guarding against this). 0.16 does not contain it at least. Would updating work for you?

**Comment by Yoric** [comment] 2018-10-09 15:32
I think that I only have one dependency that depends on lalrpop, so it should work, if I can port webidl-rs to 0.16.

**Comment by Yoric** [comment] 2018-10-10 08:56
After getting upstream to release a new version that depends on 0.16, I realize that this is *not* fixed.

Can something be done about it? It's kind of blocking me :/

**Comment by Yoric** [comment] 2018-10-10 09:15
Oh, it looks like a bug in cargo could be the cause of this on my end. Investigating.

**Comment by Yoric** [comment] 2018-10-10 12:42
Ok, as of 0.16.0, it seems to actually be a bug in Cargo, not in this crate. As far as I can tell, works for me.

**Comment by staktrace** [comment] 2018-10-16 11:03
0.16 *does* contain the lrgrammar.rs file. You can verify like so:

```
curl --location https://crates.io/api/v1/crates/lalrpop-snap/0.16.0/download > lalrpop-snap.tgz
tar xzf lalrpop-snap.tgz
wc -c lalrpop-snap-0.16.0/src/parser/lrgrammar.rs
```

which shows that it exists and is 3887355 bytes.

If you want to keep it out of the published crate it would be best to add an exclude entry to the Cargo.toml file. See https://github.com/staktrace/mailparse/blob/dc4b3220accf229e2b9d089a641d943d5202e629/Cargo.toml#L13 for an example.

**Comment by Yoric** [comment] 2018-10-16 11:06
Ouch. We should offer a simple mechanism to download and inspect crates, so that people can find out and diagnose these kinds of bugs more easily.

**Comment by Marwes** [comment] 2018-10-16 11:51
`lalrpop-snap` includes the grammar file (and always has) because it has to or there is no way to parse lalrpop grammar files in the first place. I thought the issue here was that in 0.15.2 `lalrpop` also contained the grammar file which is not necessary and it is not there in 0.16 (I verified that by looking in my ~/.cargo/registry/src` directory.

The best we can do here is that it might be possible to avoid generating some of the parsers in the lalrpop-snap grammar which would reduce the size somewhat. Not sure how many that can be removed (if any) though but hopefully all except the grammar parser itself, there rest might only be used for tests.

**Comment by Marwes** [comment] 2018-10-16 11:54
cc https://github.com/lalrpop/lalrpop/issues/333

**Comment by staktrace** [comment] 2018-10-16 14:18
Hm, you're right. The lrgrammar.rs was in previous versions of lalrpop-snap as well, and actually used to be vendored into the mozilla-central tree until the most recent vendoring which removed it. Presumably that was an accident. So I guess there's nothing to do here.

**Comment by Marwes** [comment] 2018-10-21 14:17
Got some PRs up for review now which works on reducing the size of lalrpop (in multiple respects) the final tally is a 1Mb .rs file for the grammar https://github.com/lalrpop/lalrpop/pull/414 . Reducing it further is possible but it is certainly getting more difficult and it is unclear whether the reductions will translate into binary size savings (which is what I mostly care about for these changes).

Closing this as duplicate of #333

**Closed by Marwes** 2018-10-21 14:17 UTC
